In [1]:
#install "opencv-python" library with python to use this module
import cv2

In [2]:
#to set the internal webcam as source camera,we use index 0, for external webcam we pass argument as 1
#cv2.VideoCapture(0) will return the souce camera or can say video capture object for image clicking.
cap = cv2.VideoCapture(0)

In [3]:
#while reading, it captures image in specified frame dimension from video capture object.
#it returns two values, 1st is boolean, True or False, for wether image got clicked successfully or not
#2nd value will be the image data in array format
return_value , photo = cap.read()
#to release camera after clicking pic
cap.release()

In [79]:
#to convert image data from array format to .png file and save it, will return boolean value, for sucessful or failure
cv2.imwrite("photo.png",photo)

True

In [80]:
#to show the clicked image, 1st argument will be the name of window in which image will be displayed, its upon us we can keep anyname
#2nd argument will be array data of image.
cv2.imshow("mypic1", photo)
#this will hold the image for specified time, and if we want to manually close the pic display, then don't pass any argument, then pic will be displayed for infinite time
cv2.waitKey(20000)
#after displaying the image, it will destroy the window in which pic displayed, and prevent our running application from crashing
cv2.destroyAllWindows()


In [7]:
#for saving & displaying grey scale image , with R=G=B concept
#to create colourful image, we need 3D array, with depth =3, but for grey scaled image only 2 D array is required or 3D array with depth = 1 will be enough.
#import numpy as np
ph=photo[:,:,0]+photo[:,:,1]+photo[:,:,2]
#ph=ph/3
#ph=ph[:,:,np.newaxis]
#aphoto = np.concatenate((ph, ph), axis=2)                        #as grey scaled image doesn't need 3D array so, we ommented it.
#final_photo = np.concatenate((aphoto, ph), axis=2)
cv2.imwrite("mypic2.jpg", ph)
cv2.imshow("mypic2", ph)
cv2.waitKey(20000)
cv2.destroyAllWindows()

In [85]:
#for displaying perfect grey scaled pic, with using a cv2 function.
cphoto = cv2.cvtColor(photo, cv2.COLOR_BGR2GRAY)
cv2.imshow("mypic3", cphoto)
cv2.waitKey(20000)
cv2.destroyAllWindows()

In [86]:
#for saving grey scale image , with Grey = 0.299*R + 0.587*G + 0.114*B concept
import numpy as np
p=0.299*photo[:,:,0]+ 0.587*photo[:,:,1]+ 0.114*photo[:,:,2]
p=p/3
cv2.imwrite("mypic4.jpg", p)


True

In [82]:
cphoto

array([[  2,   2,   9, ..., 206, 208, 210],
       [  2,   2,   8, ..., 208, 209, 209],
       [  2,   2,   8, ..., 209, 209, 209],
       ...,
       [ 63,  61,  57, ...,   7,   8,   8],
       [ 65,  61,  62, ...,   4,   6,   4],
       [ 64,  63,  71, ...,   6,   4,   3]], dtype=uint8)

In [83]:
p

array([[ 0.701     ,  1.03433333,  0.567     , ..., 67.598     ,
        67.52933333, 68.29566667],
       [ 0.701     ,  0.93466667,  0.        , ..., 67.567     ,
        68.26466667, 68.26466667],
       [ 1.03433333,  0.701     ,  0.        , ..., 67.30233333,
        67.50166667, 67.50166667],
       ...,
       [20.907     , 20.24033333, 19.144     , ...,  1.86933333,
         2.33666667,  2.33666667],
       [21.24033333, 20.00666667, 20.20933333, ...,  0.93466667,
         1.63566667,  1.16833333],
       [21.041     , 20.70766667, 21.97566667, ...,  1.16833333,
         1.16833333,  0.93466667]])

In [84]:
ph

array([[ 4.66666667,  4.66666667,  2.66666667, ..., 28.33333333,
        26.33333333, 23.66666667],
       [ 3.33333333,  3.33333333,  3.33333333, ..., 29.66666667,
        27.66666667, 28.66666667],
       [ 2.66666667,  2.66666667,  3.33333333, ..., 26.33333333,
        27.        , 29.66666667],
       ...,
       [53.        , 60.        , 62.33333333, ...,  6.33333333,
         4.        ,  2.66666667],
       [58.66666667, 61.66666667, 61.33333333, ...,  4.66666667,
         4.        ,  2.66666667],
       [61.33333333, 64.66666667, 59.66666667, ...,  3.33333333,
         2.66666667,  1.33333333]])